name: ThinkMap
version: 0.2
description: Displays a 3D render of your server's map in the browser
author: Thinkofdeath

main: uk.co.thinkofdeath.thinkmap.bukkit.ThinkMapPlugin
load: STARTUP

commands:
   thinkmap:
     description: TODO
     aliases: [thinkmap]
     permission: thinkmap.command
     usage: N/A