library map_viewer;

import "dart:html";
import "dart:web_gl";
import "dart:async";
import "dart:typed_data";
import "dart:math";
import "dart:convert";
import "dart:js";
import "package:vector_math/vector_math.dart";

part "src/main.dart";
// Rendering
part "src/rendering.dart";
part 'src/renderers/webgl/renderer.dart';
part "src/renderers/webgl/shaders.dart";
part "src/renderers/webgl/pool.dart";
part "src/renderers/webgl/block_builders.dart";
part "src/renderers/webgl/utils.dart";
part "src/renderers/webgl/chunk.dart";
part "src/renderers/webgl/world.dart";
// World
part "src/world.dart";
part "src/chunk.dart";
// Blocks
part "src/box.dart";
part "src/registry.dart";
part "src/block.dart";
//part "src/blocks/otherblocks.dart";
//part "src/blocks/grass.dart";
//part "src/blocks/cross.dart";
//part "src/blocks/vines.dart";
//part "src/blocks/sign.dart";
// Network
part "src/network.dart";
// Other
part "src/support.dart";
part "src/logging.dart";
